name: Deploy Laravel to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      # 3. Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 4. Prepare application key
      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

      # 5. Setup Node and build frontend assets
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build


      # 5. Deploy to Shared Hosting
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/grxngcrukci1/public_html/test.huma-volve.com

            git fetch origin
            git reset --hard origin/main

            composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear

            php artisan optimize
